version: '3.1'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports: [80:80]
    volumes: [.:/var/www/html,./.htaccess:/var/www/html/.htaccess]

  db:
    image: mysql
    command:
      [
        sh,
        -cx,
        "mysqld -uroot --default-authentication-plugin=mysql_native_password && mysql> GRANT ALL PRIVILEGES  ON *.* TO 'shadowflade'@'localhost'",
      ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: news
    ports: [3000:3000]
    expose:
      - 3000

  adminer:
    image: adminer
    restart: always
    ports: [8080:8080]
